// Экспорт shared компонентов
export { ThemeSwitcher } from './ThemeSwitcher'
export { LoadingFallback } from './LoadingFallback'
export { LazyErrorBoundary } from './LazyErrorBoundary'
export { FilterChips } from './FilterChips'
export { PageInfoBlock } from './PageInfoBlock'
export type { PageInfoBlockProps, PageDescription } from './PageInfoBlock'
export { EmptyState } from './EmptyState'
export type { EmptyStateProps } from './EmptyState'
export { PageBreadcrumbs } from './PageBreadcrumbs'
export { WorkflowIndicator, WORKFLOW_STEPS } from './WorkflowIndicator'
export type { WorkflowIndicatorProps } from './WorkflowIndicator'
export * from './LazyComponents'
